notification.property=Notification Profile Dev

# Configuración de Spring Mail
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.debug=true

# Configuración de Twilio
twilio.whatsapp.phone.number=+14155238886
twilio.phone.number=+12314471107